### ISSUE TITLE
14 realms causes crash

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#511] opened 2021-04-07 18:31 UTC
I found this while reviewing https://github.com/keycloak/keycloak-admin-ui/pull/502.  But it happens in master as well.  Apparently, if you create 14 realms, whoami and serverinfo requests will fail with 431 status "Request Header Fields Too Large".

This works fine in the old console.

**Comment by edewit** [comment] 2021-04-08 12:10
I can't reproduce this, I created sixteen realms:

```
0: {id: "298b165a-2baa-4bee-be26-136f7341f873", realm: "tweleve", notBefore: 0, revokeRefreshToken: false,…}
1: {id: "2a50dacc-29d5-44b3-8a98-700a64940ec8", realm: "nine", notBefore: 0, revokeRefreshToken: false,…}
2: {id: "51995f79-5912-4114-b1b3-b5d502570c5b", realm: "another", notBefore: 0, revokeRefreshToken: false,…}
3: {id: "661e1e87-8c2a-448c-8e8a-d0f329638809", realm: "eight", notBefore: 0, revokeRefreshToken: false,…}
4: {id: "6f651e68-d273-424a-83ae-37517e344e37", realm: "fifteen ", notBefore: 0,…}
5: {id: "83df054f-01e6-4d63-9131-7ecd0f12d090", realm: "super", notBefore: 0, revokeRefreshToken: false,…}
6: {id: "8d64255e-adc4-41b4-b66a-1720838fd731", realm: "seven", notBefore: 0, revokeRefreshToken: false,…}
7: {id: "97888a8a-13d2-47a3-918a-167345dac151", realm: "super2", notBefore: 0, revokeRefreshToken: false,…}
8: {id: "a184e06a-5a4c-4e6c-b75e-91823123c8d2", realm: "ten", notBefore: 0, revokeRefreshToken: false,…}
9: {id: "ac671372-b186-4743-bd16-3732702b5968", realm: "fourteen", notBefore: 0,…}
10: {id: "ad7c5adf-3b0a-408a-8c45-cdfffd818ab8", realm: "five", notBefore: 0, revokeRefreshToken: false,…}
11: {id: "b75ecdb7-23cd-4afb-8172-7bdbc88a120c", realm: "eleven", notBefore: 0, revokeRefreshToken: false,…}
12: {id: "c7af10fa-1219-4713-957e-7815625364c1", realm: "thirteen", notBefore: 0,…}
13: {id: "c8f47454-4900-4c82-8dc6-aaf44dcf382c", realm: "four", notBefore: 0, revokeRefreshToken: false,…}
14: {id: "d039d3e4-e525-4b21-a17f-1ed3c21050fc", realm: "six", notBefore: 0, revokeRefreshToken: false,…}
15: {id: "d7ad8b50-10ff-42c3-bda2-a609604b56ff", realm: "one", notBefore: 0, revokeRefreshToken: false,…}
16: {id: "master", realm: "master", displayName: "Keycloak",…}
```

**Comment by ssilvert** [comment] 2021-04-08 19:18
@edewit I looked at this some more and I found that the bearer token gets larger and larger each time you add a new realm.  Just take a look at the `Authorization` request header on the whoami request.  If you keep adding realms it will eventually get large enough to cause a 431 error.

This doesn't happen in the old console.  I'm thinking that this might be a bug in the admin client?

**Comment by edewit** [comment] 2021-04-09 06:36
the admin client is not used to authenticate just to do the requests for authentication we use `keycloak-js` I'll investigate

**Comment by edewit** [comment] 2021-04-12 08:37
I see the token contains all the `resource_access`, because of this we refresh it after a realm has been created. So it should also happen in the old console!

```json
  "resource_access": {
    "thirteen-realm": {
      "roles": [
        "view-realm",
        "view-identity-providers",
        "manage-identity-providers",
        "impersonation",
        "create-client",
        "manage-users",
        "query-realms",
        "view-authorization",
        "query-clients",
        "query-users",
        "manage-events",
        "manage-realm",
        "view-events",
        "view-users",
        "view-clients",
        "manage-authorization",
        "manage-clients",
        "query-groups"
      ]
    },
```

**Comment by edewit** [comment] 2021-04-13 09:50
okay this seems to be related to the client configuration when it has `fullScopeAllowed` set to true it adds the resource_access, but without it we don't have access

**Comment by edewit** [comment] 2021-04-15 09:06
@ssilvert can we close this issue? It's a client configuration and not an issue in the front-end

**Comment by jonkoops** [comment] 2021-08-04 10:40
Closing this issue as it's not a problem with the front-end

**Closed by jonkoops** 2021-08-04 10:40 UTC
