### ISSUE TITLE
Unable to view/reset all list items to initial state after filtering

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak-admin-ui#1855] opened 2022-01-12 11:40 UTC
### Describe the bug

In **Client scopes**, after filtering list items by Protocol -> SAML and select back filter by Name and press Search button, does not list all items.
 
 

### Version

Keycloak 16.1.0 (WildFly Core 18.0.0.Final)

### Expected behavior

Should allow reset filter and show all items as they were previously listed without any filter applied.

### Actual behavior

Does not list all items in initial state after filtering.

### How to Reproduce?

1. Go to **Client scopes**
2. Select filter drop-down _Protocol_ -> _SAML_
3. Observe that only 1 items is listed, if exists SAML
4. Select filter drop-down _Name_ and click Search button.
5. No way to reset filter to list all items from the screen

### Anything else?

Same behavior in Clients - > Clients scopes

**Comment by jonkoops** [comment] 2022-01-17 11:18
When I am filtering by protocol all my SAML client scopes seem to show up as expected. I feel like this might be a larger issue caused by the fact that we are filtering a paginated result on the client. Since we cannot filter the results by a specific protocol on the API we only retrieve a single page, that page might not have all of the available SAML client scopes in it.

@ssilvert I think we need to make a hard decision here on if we want to include this functionality. In my opinion it is not realistic to fix this issue on the client side, we really need a better API to facilitate this. So I think we have two options here:

1. We implement this functionality on the API
2. We drop the filtering functionality 

I can confirm the other issue of being unable to clear the filters, I've created a new issue (#1874) for that so we can resolve it separately.

**Comment by ssilvert** [comment] 2022-01-17 13:37
@jonkoops Yes, we need to drop the functionality until we can implement it properly.

@edewit Can you make sure the required back end change is included in our list that we gave to Hynek's team?

**Comment by jonkoops** [comment] 2022-01-17 14:48
I've created #1875 to remove this code, we can revert the commit when we have a working API.

**Comment by edewit** [comment] 2022-01-17 14:50
@ssilvert yes it's on the list

**Comment by jonkoops** [comment] 2022-01-17 15:14
Ahh, my bad. After closer inspection this behavior is covered by the API as it is not paginated, instead it's all happening client-side. I think we can come up with a fix for this issue.

**Closed** 2022-03-14 10:15 UTC
Labels: kind/bug, area/needs-api, impact/medium, area/section/client scopes
