### ISSUE TITLE
[UX Review] Add the "Logout settings" in the OIDC client settings pgae

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1896] opened 2022-01-20 07:25 UTC
### Describe the bug

@edewit I've reviewed the OIDC client settings page and found that there is a settings group named "Logout settings" missed. We can add this group under the "Login settings" as shown in the screenshot below. In addition, the group link should be added in the "Jump to section".
 
<img width="678" alt="Screen Shot 2022-03-01 at 11 06 37 AM" src="https://user-images.githubusercontent.com/53931519/156097375-f98efc59-c4de-4415-9185-6bf32eca8efd.png">

### Version

New admin UI

**Comment by edewit** [comment] 2022-02-28 13:39
@xianli123 seems that the screenshot is missing and the Logout settings is there?
![image](https://user-images.githubusercontent.com/51133/155992680-ee6a7045-2bb2-4174-ae1c-da0deb57d4dd.png)

**Comment by xianli123** [comment] 2022-03-01 03:21
@edewit  I added the screenshot. As shown in the screenshot below, there are 5 fields in the "Logout settings". In addition, there are some other updates of client settings that need to be fixed. Please check the link here: https://github.com/keycloak/keycloak-admin-ui/issues/1968. And I found that Jenny has taken over that issue #1968, maybe we can fix these 2 issues simultaneously. What do you think?

<img width="678" alt="Screen Shot 2022-03-01 at 11 06 37 AM" src="https://user-images.githubusercontent.com/53931519/156098155-559f31f4-abe4-42e0-8301-c162685ea7f1.png">

**Comment by edewit** [comment] 2022-03-01 05:51
right so #1968 is a duplicate of this?

**Comment by xianli123** [comment] 2022-03-01 06:04
Not exactly. https://github.com/keycloak/keycloak-admin-ui/issues/1968 includes the "Logout settings" update, but it has some other changes.

**Closed** 2022-03-02 21:59 UTC
Labels: kind/bug, impact/high, area/section/clients
