### ISSUE TITLE
Google Identity Provider hosted Domain parameter not visible

### ISSUE THREAD

**Issue by rpahli** [keycloak/keycloak-admin-ui#3083] opened 2022-08-09 08:39 UTC
### Describe the bug

The `hostedDomain` parameter for google is not visible in he UI and cannot be configured.

### Version

19.0.1

### Expected behavior

for google IP the `hostedDomain` parameter should be visible.

**Comment by ssilvert** [comment] 2022-08-09 18:58
@rpahli Thanks for reporting.  I'm closing this as a duplicate of https://github.com/keycloak/keycloak-admin-ui/issues/3089

**Closed by ssilvert** 2022-08-09 18:58 UTC
Labels: kind/bug, status/triage
