### ISSUE TITLE
Save/Revert toolbar covers content

### ISSUE THREAD

**Issue by kherock** [keycloak/keycloak-admin-ui#2983] opened 2022-07-18 17:23 UTC
### Describe the bug

The floating toolbar at the bottom of Client and Identity provider settings obscures the last field on the page if the viewport isn't tall enough:

![image](https://user-images.githubusercontent.com/4993980/179567496-6303d644-0fc3-44fe-8383-c11ff4487ccd.png)

### Version

18.0.2

### Expected behavior

This should be fixable with some additional padding at the bottom of the form's container

**Comment by jonkoops** [comment] 2022-07-29 10:18
I can confirm this is still an issue, marking this as something we should try to resolve before the next patch release.

**Comment by edewit** [comment] 2022-08-04 09:00
I can't reproduce this, seems this has been fixed

**Comment by dominikkawka** [comment] 2022-08-04 10:27
> I can't reproduce this, seems this has been fixed

Check #3053

**Closed** 2022-08-04 12:14 UTC
Labels: kind/bug, priority/important, impact/medium, area/section/clients, area/section/identity providers
