### ISSUE TITLE
"Unexpected token u in JSON at position 0" error when opening identity provider mappers created in a previous Keycloak version

### ISSUE THREAD

**Issue by vpmuli** [keycloak/keycloak-admin-ui#3048] opened 2022-08-04 06:59 UTC
### Describe the bug

The new admin UI displays "Unexpected token u in JSON at position 0" error when opening identity provider mappers created in a previous Keycloak version, for example 18.0.2. This prevents the user from viewing or editing the mapper.

### Version

19.0.1

### How to Reproduce?

- Create an identity provider mapper in 18.0.2
- Upgrade to Keycloak 19.0.1
- Open the identity provider mapper in the new admin UI

### Anything else?

The error seems to be related to the config.claims field that is missing from the identity provider mapper created in 18.0.2. When that field is added to the database the mapper can be opened without error.

**Comment by ssilvert** [comment] 2022-08-04 19:32
@vpmuli Thanks for reporting.

Note: You don't have to downgrade to 18.0.2 to see the bug.  You only need to create the mapper with the old console and then go to the new console and view it.

**Comment by horus** [comment] 2022-08-08 07:09
Almost the same here. I constantly got one of the following:
- `JSON Parse error: Unexpected identifier "undefined"` (Safari)
- `"undefined" is not valid JSON` (Chrome)
- `JSON.parse: unexpected character at line 1 column 1 of the JSON data` (Firefox)

The object with `config.claims` field defined still made the error show up.
In my case it was probably caused by the absent of `config.attributes` I guess.

**Comment by edewit** [comment] 2022-08-08 07:51
duplicate of #3022 addressed by #3035

**Closed** 2022-08-09 12:04 UTC
Labels: kind/bug, impact/high, area/section/identity providers
