### ISSUE TITLE
User Storage Provider settings not visible in admin UI

### ISSUE THREAD

**Issue by SebastianLng** [keycloak/keycloak-admin-ui#3059] opened 2022-08-05 10:19 UTC
### Describe the bug

I am currently trying to migrate my User Storage SPI implementation to keycloak 19. I have a small test project where I tried to port the storage provider according to the migration guides first. This means, as I understand it, using the legacy packages and using the LegacyUserCredentialManager for the user class. The keycloak 19 storage provider seems to work in in principal, but the configuration properties are not shown in the new admin UI.

### Version

19.0.1

### Expected behavior

The new admin UI in keycloak 19 shows the custom provider properties in the UI.

### Actual behavior

Keycloak 18 shows the properties:

![kc-18-settings](https://user-images.githubusercontent.com/25402641/183056690-0524a4e9-2599-47c2-9093-58d988d255f5.png)
The new admin UI in Keycloak 19 doesn't show any custom properties:
![kc-19-settings](https://user-images.githubusercontent.com/25402641/183056730-cf0748b0-9983-487d-bdf1-b983f69ac52e.png)

### How to Reproduce?

How to Reproduce?
- Create a user storage SPI with legacy storage and provider config properties.
- Run Keycloak 19 in dev mode with the custom storage provider

Here're my small keycloak 18 and 19 test projects to reproduce the issue:
[test-storage-provider.zip](https://github.com/keycloak/keycloak-admin-ui/files/9267737/test-storage-provider.zip)

### Anything else?

Moved from https://github.com/keycloak/keycloak/issues/13535

**Comment by edewit** [comment] 2022-08-08 07:36
fixed in https://github.com/keycloak/keycloak-admin-ui/pull/3042

**Closed by edewit** 2022-08-08 07:36 UTC
Labels: kind/bug, impact/high, area/section/user federation

**Comment by nathmo** [comment] 2022-08-16 16:23
hey @SebastianLng  did you try with the old theme ? i had a similar issue and it turned out to be the theme that was set to keycloak.v2 instead of keycloak

**Comment by edewit** [comment] 2022-08-18 06:59
@nathmo right that is what the issue is about that it didn't work in keycloak.v2, but it's fixed now
