### ISSUE TITLE
Authorization resource page displays incorrect associated scope based permissions

### ISSUE THREAD

**Issue by hean0224** [keycloak/keycloak-admin-ui#2386] opened 2022-04-01 17:33 UTC
### Describe the bug

On the resource page of the authorization server.  All resources that share the same resource type will display associated scope permissions that are specific to a single resource.

### Version

9.0.3,15.1.1

### Expected behavior

Only scope based permission associated to that particular resource should be shown.

### Actual behavior

All resources with the same resource type will display all scope based permissions associated to any resource with the same type.

### How to Reproduce?

[temp.json.txt](https://github.com/keycloak/keycloak-admin-ui/files/8399783/temp.json.txt) <--realm file

Review resource1 and resource2.  Both share a resource type of "same".  scope based permission:resource1 is associated to resource1, scope based permssion:resource2 is associated to resource2.  In the UI on the resource page, it shows both permissions associated to both resource1 and resource2.
![resourceUI](https://user-images.githubusercontent.com/44619069/161313044-ce25e38b-f5ec-4a54-b7f4-db9a227008fc.jpg)
.

### Anything else?

I current have a 9.0.3 instance that shows this behavior and a 15.1.1.  I attached the 15.1.1 realm export.

Sorry if I said scope  based permission multiple times.  I didn't want anyone to assume is was a resource based (resource type) permission which I would expect to be proper behavior.

**Comment by ssilvert** [comment] 2022-04-05 23:58
@hean0224 Thanks for reporting this.

**Comment by edewit** [comment] 2022-04-06 10:58
This is a backend issue the UI just calls:
```
GET /admin/realms/master/clients/83530999-5569-4bd6-87ad-1f23da72ebc7/authz/resource-server/resource/0a4af22a-e27b-47a7-9acf-a74df29393d0/permissions

[
   {
      "id":"bc0f6fb3-2773-4d9e-ae82-0428a52f48c8",
      "name":"permission:resource1",
      "type":"scope",
      "logic":"POSITIVE",
      "decisionStrategy":"UNANIMOUS",
      "config":{
         
      }
   },
   {
      "id":"4b246fd0-f552-4367-9620-01d5c62c3e0f",
      "name":"permission:resource2",
      "type":"scope",
      "logic":"POSITIVE",
      "decisionStrategy":"UNANIMOUS",
      "config":{
         
      }
   }
]
```
but it should only return the one...

**Comment by pedroigor** [comment] 2022-04-07 22:03
@hean0224 Can we close this one in favor of https://github.com/keycloak/keycloak/issues/11148?

I'm working on it.

**Comment by ssilvert** [comment] 2022-04-08 16:21
I think we should leave this open until https://github.com/keycloak/keycloak/issues/11148 is closed.  

We need to be able to easily list the blockers for new Admin UI, even if the problem is not in our code.

**Comment by edewit** [comment] 2022-04-21 08:45
fixed and verified against the nightly version of keycloak

**Closed by edewit** 2022-04-21 08:45 UTC
Labels: kind/bug, impact/high, area/section/clients
